### PR TITLE
Property access support (EXPERIMENTAL)

### PR DESCRIPTION
**Pull request by NagyGa1**
Hi,
This works for my test cases and application, hope it fits to the overall picture. It passes the original tests as well.

### CODE REVIEW

**Comment by nociar** [comment]
Hello Gabor, thank you for your contribution. I have quickly looked through the sources. The sources are really nice, but... :-) Please note that access type support needs to consider following:

- @Access + @AccesType annotations can be applied on @Entity, @MappedSuperclass, @Embeddable or a specific attribute (there are some nasty rules in the JPA spec) :-)
- the @Embeddable classes do not have any @Id - the JpaClassInfo#accessType will be NULL
- @MappedSuperclass may have @Id (but not necessarily)

And finally - JPA classes may have mixed attribute access. Some people are using JPA and non-JPA attributes in their classes. The upper implementation would omit non-JPA fields in the cloning process for the PROPERTY access type. These problems were the motivation why I decided to support only the field access... :-(

Unfortunately this pull request may have breaking changes to many users. But I will re-release this project under the Apache 2.0 licence soon. You will be able to apply the changes in your project to fit your needs. I will think about the PROPERTY access type support during my free time which has really shortened after my daughter birth... :-)

**Comment by NagyGa1** [comment]
Hi Miroslav,

Thank you.

I forgot to put it somewhere in the documentation that if the code does not detect property access, it falls back to the old behaviour.

I can add on parsing for @Access + @AccessType annotation tomorrow.

With that, should I just keep that in the fork, or send a pull request?

**Comment by nociar** [comment]
Hello, sure you can continue in the fork. But please consider also mixed access types: http://thebrainyprofessionals.com/2013/05/26/mixed-access-types-in-jpa/

Also think about following classes:
```java
@Entity
@Acces(AccesType.PROPERTY)
public class Foo {
    private int a;
    private int b;
    public int getA() {
        return this.a;
    }
    public void setA(int a) {
        this.a = a;
    }
    public void increment() {
        b++;
    }
}
```
Both fields (a, b) need to be cloned. But PROPERTY access handles only attribute A.

```java
@Entity
@Acces(AccesType.PROPERTY)
public class Foo {
    private int a;
    private int b;
    public int getA() {
        return this.b;
    }
    public void setA(int a) {
        this.b = a;
    }
    public void increment() {
        a++;
    }
}
PropertyFilter currently handles field names, not property names. This will lead to confusion as getA()/setA() handles value of "b".

I believe that the PROPERTY access support will need more investigation and probably refactoring/braking changes. But as I wrote, I will re-release this project under the Apache license. You will be able to adapt the changes to fit your needs...

**Comment by NagyGa1** [comment]
Thank you, and good luck with your kid!

**Comment by nociar** [comment]
Reopening pull request (accidentally closed)

**Comment by nociar** [comment]
Hello Gabor, I have checked out the branch feat_support_property_access. I will try to merge the changes. May be I will something change :-) Thank you for the effort!

**Comment by NagyGa1** [comment]
Thank you very much, hope it will work.

If it is merged, I will delete the fork.

**Pull request merged**
